### ISSUE TITLE
Deprecated notice: 

### ISSUE THREAD

**Issue by t-me** [cliffparnitzky/ExtendedMemberInserttags#2]
When i open the package manager i get this error.
When i remove this plugin the error is gone.
i'm using contao version : 3.5.4

	Deprecated notice: The Composer\Package\LinkConstraint\VersionConstraint class is deprecated, use Composer\Semver\Constraint\Constraint instead. in phar://composer/composer.phar/src/Composer/Package/LinkConstraint/VersionConstraint.php on line 17
	#0 [internal function]: __error(16384, 'The Composer\\Pa...', 'phar:///home/de...', 17, Array)
	#1 phar://composer/composer.phar/src/Composer/Package/LinkConstraint/VersionConstraint.php(17): trigger_error('The Composer\\Pa...', 16384)
	#2 vendor/composer/ClassLoader.php(412): include('phar:///home/de...')
	#3 vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('phar:///home/de...')
	#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Composer\\Packag...')
	#5 system/modules/!composer/templates/be_composer_client_install.html5(30): spl_autoload_call('Composer\\Packag...')
	#6 system/modules/core/library/Contao/BaseTemplate.php(88): include('/home/deb...')
	#7 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
	#8 system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
	#9 system/modules/!composer/src/Controller/DetailsController.php(101): Contao\BackendTemplate->parse()
	#10 system/modules/!composer/src/ClientBackend.php(218): ContaoCommunityAlliance\Contao\Composer\Controller\DetailsController->handle(Object(Contao\Input))
	#11 system/modules/core/classes/Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
	#12 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('composer')
	#13 contao/main.php(20): Contao\BackendMain->run()
	#14 {main}

	Deprecated notice: The Composer\Package\LinkConstraint\LinkConstraintInterface interface is deprecated, use Composer\Semver\Constraint\ConstraintInterface instead. in phar://composer/composer.phar/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php on line 17
	#0 [internal function]: __error(16384, 'The Composer\\Pa...', 'phar:///home/de...', 17, Array)
	#1 phar://composer/composer.phar/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php(17): trigger_error('The Composer\\Pa...', 16384)
	#2 vendor/composer/ClassLoader.php(412): include('phar:///home/de...')
	#3 vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('phar:///home/de...')
	#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Composer\\Packag...')
	#5 phar://composer/composer.phar/src/Composer/Package/LinkConstraint/VersionConstraint.php(23): spl_autoload_call('Composer\\Packag...')
	#6 vendor/composer/ClassLoader.php(412): include('phar:///home/de...')
	#7 vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('phar:///home/de...')
	#8 [internal function]: Composer\Autoload\ClassLoader->loadClass('Composer\\Packag...')
	#9 system/modules/!composer/templates/be_composer_client_install.html5(30): spl_autoload_call('Composer\\Packag...')
	#10 system/modules/core/library/Contao/BaseTemplate.php(88): include('/home/deb...')
	#11 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
	#12 system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
	#13 system/modules/!composer/src/Controller/DetailsController.php(101): Contao\BackendTemplate->parse()
	#14 system/modules/!composer/src/ClientBackend.php(218): ContaoCommunityAlliance\Contao\Composer\Controller\DetailsController->handle(Object(Contao\Input))
	#15 system/modules/core/classes/Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
	#16 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('composer')
	#17 contao/main.php(20): Contao\BackendMain->run()
	#18 {main}

**Comment by cliffparnitzky** [comment]
This ist a composer plugin issue. Please have a lokk at the community: https://community.contao.org/de/showthread.php?59785-Deprecated-notice-gt-Package-LinkConstraint-%E4ndern-in-Semver-Constraint-wo-und-wie
