### ISSUE TITLE
zusätzliche Felder werden nicht angezeigt....

### ISSUE THREAD

**Issue by martin334a** [cliffparnitzky/ExtendedMemberInserttags#4]
Hallo!
Ich habe die Erweiterung ohne Probleme installieren können.
Installiert wurde  in:
meine-domain.at/vendor/cliffparnitzky/extended-member-inserttags/

Leider werden die zusätzlichen Felder nicht im Backend angezeigt.
Habe keine Lösung dafür gefunden....

**Comment by cliffparnitzky** [comment]
Die Erweiterung stellt keine Felder zur Verfügung, nur Inserttags: https://github.com/cliffparnitzky/ExtendedMemberInserttags#insert-tags

**Comment by martin334a** [comment]
ah OK - Danke für die Rückmeldung.
... dann schreib ich mir die Felder in eine tl_member.php datei plus language / de.....
